
module Nawashi
  PRELUDE = %Q{
    use nawashi
    import nawashi
  }

  AUTOGEN_NOTICE = %Q{
// Code auto-generated by Nawashi v#{Nawashi::VERSION}, don't edit by hand!
// Or, you know, do. But don't cry if it's overwritten.
// https://github.com/fasterthanlime/nawashi
}
end
